Update ga-track-fold to ES6
firstandthird/ga-track-fold pull request #3
Opened 2017-10-03 19:05 UTC by dannyvink

Updated to the latest ga-track dependency and converted syntax to ES6.

2017-10-05 10:10 UTC, Antonio-Laguna requested changes
Great work here @dannyvink 

Few minor comments

2017-10-05 10:10 UTC, Belelros commented on index.js
> +import Cookies from 'js-cookie';
We should use https://github.com/firstandthird/cookie-monster to handle cookies

2017-10-05 10:10 UTC, Belelros commented on test/ga-track-fold.test.js
> +window._gaq = { // eslint-disable-line no-underscore-dangle
Probably disable for entire file with `eslint-disable` on top

2017-10-06 16:46 UTC, dannyvink commented
Changes made!

2017-10-06 18:00 UTC, Antonio-Laguna approved these changes

2017-10-06 18:00 UTC, Belelros commented
LGTM

2017-10-09 11:11 UTC, merged